baseURL = 'https://cadot-eu.github.io'
languageCode = 'fr-FR'
title = 'Cadot.eu Company blog'
theme = "m10c"
[params]
  author = "Christopher Hart"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/cadot-eu"
[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"

