baseURL = 'https://cadot-eu.github.io'
languageCode = "en-us"
title = 'Cadot.eu Company blog'
theme = "m10c"

[params]
  author = "Cadot.eu"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/cadot-eu"


